import { chromium } from 'playwright-core';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage();
const failures = [];
const ok = (x) => console.log('  ok  ', x);
const bad = (x) => { console.log('  FAIL', x); failures.push(x); };
await page.goto('http://localhost:4184/CalculadoraMilitar/', { waitUntil: 'networkidle' });
const text = async () => (await page.locator('body').innerText()).toLowerCase();
const ficha = page.getByRole('button', { name: /1\. ficha do cidadão/i });
const reserva = page.getByRole('button', { name: /2\. obrigações e reserva/i });
await ficha.click();
(await text()).includes('data do alistamento') ? ok('modo inicial mostra Ficha') : bad('Ficha não abriu');
(await text()).includes('faltas exar:') ? bad('EXAR visível no modo alistamento') : ok('EXAR oculto no modo alistamento');
await page.locator('input[type="date"]').fill('2026-08-20');
await reserva.click();
(await text()).includes('faltas exar:') ? ok('modo reserva mostra EXAR') : bad('EXAR não abriu');
(await text()).includes('data do alistamento') ? bad('Ficha continua visível no modo reserva') : ok('Ficha oculta no modo reserva');
const exarInput = page.locator('section').nth(1).locator('input[type="number"]').first();
await exarInput.fill('1');
await page.waitForTimeout(150);
(await text()).includes('falta exar') ? ok('modo reserva calcula EXAR') : bad('EXAR não entrou no extrato');
await ficha.click();
(await text()).includes('data do alistamento') ? ok('volta para Ficha') : bad('não voltou para Ficha');
(await text()).includes('falta exar') ? bad('multa EXAR vazou para modo alistamento') : ok('multa EXAR isolada');
await browser.close();
console.log(failures.length ? `${failures.length} falha(s)` : 'TUDO OK');
if (failures.length) process.exit(1);
